steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "GOOGLE_PROJECT_ID=$_GOOGLE_PROJECT_ID",
        "--build-arg",
        "GOOGLE_TRANSLATE_API_KEY=$_GOOGLE_TRANSLATE_API_KEY",
        "--build-arg",
        "FIREBASE_PROJECT_ID=$_FIREBASE_PROJECT_ID",
        "--build-arg",
        "FIREBASE_CLIENT_EMAIL=$_FIREBASE_CLIENT_EMAIL",
        "--build-arg",
        "FIREBASE_PRIVATE_KEY=$_FIREBASE_PRIVATE_KEY",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_API_KEY=$_NEXT_PUBLIC_FIREBASE_API_KEY",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$_NEXT_PUBLIC_FIREBASE_PROJECT_ID",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_APP_ID=$_NEXT_PUBLIC_FIREBASE_APP_ID",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID",
        "--build-arg",
        "NEXT_PUBLIC_URL=$_NEXT_PUBLIC_URL",
        "--build-arg",
        "NEXT_PUBLIC_BASE_URL=$_NEXT_PUBLIC_BASE_URL",
        "--build-arg",
        "NEXTAUTH_PUBLIC_URL=$_NEXTAUTH_PUBLIC_URL",
        "--build-arg",
        "NEXTAUTH_SECRET=$_NEXTAUTH_SECRET",
        "--build-arg",
        "NEXTAUTH_URL=$_NEXTAUTH_URL",
        "--build-arg",
        "NODE_ENV=$_NODE_ENV",
        "--build-arg",
        "OPENAI_API_KEY=$_OPENAI_API_KEY",
        "-t",
        "gcr.io/$PROJECT_ID/zhongwen-advantage",
        ".",
      ]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/zhongwen-advantage"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "zhongwen-advantage",
        "--image",
        "gcr.io/$PROJECT_ID/zhongwen-advantage",
        "--timeout=60m",
        "--region",
        "asia-southeast1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

images:
  - gcr.io/$PROJECT_ID/zhongwen-advantage

options:
  logging: CLOUD_LOGGING_ONLY
