name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate Docker to Google Cloud Registry
        run: gcloud auth configure-docker

      - name: Build and Deploy
        run: |
          gcloud builds submit --config cloudbuild.yaml \
            --substitutions _GOOGLE_PROJECT_ID=${{ secrets.GOOGLE_PROJECT_ID }},\
            _GOOGLE_TRANSLATE_API_KEY=${{ secrets.GOOGLE_TRANSLATE_API_KEY }},\
            _FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }},\
            _FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }},\
            _FIREBASE_PRIVATE_KEY='${{ secrets.FIREBASE_PRIVATE_KEY }}',\
            _NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }},\
            _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }},\
            _NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }},\
            _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }},\
            _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }},\
            _NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }},\
            _NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }},\
            _NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }},\
            _NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }},\
            _NEXTAUTH_PUBLIC_URL=${{ secrets.NEXTAUTH_PUBLIC_URL }},\
            _NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }},\
            _NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }},\
            _NODE_ENV=${{ secrets.NODE_ENV }},\
            _OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
